# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"
  # config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 8002, host: 8002


  # Shared folders
  config.vm.synced_folder "../", "/home/vagrant/cheat"

  #SSH connections made will enable agent forwarding.
  config.ssh.forward_agent = true

  # X Windows for emacs and IDE
  config.ssh.forward_x11 = true
  config.ssh.insert_key = false

  # Provider-specific configuration so you can fine-tune various
  config.vm.provider :virtualbox do |vb|
    vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id,
                  "--memory", "1024",
                  "--cpus", 2,
                  "--name", "junk-vagrant"]
  end

  config.vm.provision "shell", privileged: false, path: "provision.sh"

end

